config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :breeders do
    resources :comments
  end

  resources :products do
    resources :orders
  end

  
  
  resources :users
  root 'static_pages#home'
  
  get 'users'    => 'users#index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  match '/searched', to: 'search#search', via: 'get'
  match '/searchesed', to: 'searches#searches', via: 'get'

end

app/models/breeder.rb
class Breeder < ActiveRecord::Base
   has_attached_file :image, styles: { large: "500x500#", medium: "400x400#", :thumb => "150x150#" }
   validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
   belongs_to :user
   has_many :comments
end

app/controllers/breeders_controller.rb
class BreedersController < ApplicationController
  before_action :set_breeder, only: [:show, :edit, :update, :destroy]

  # GET /breeders
  # GET /breeders.json
  def index
    @breeders = Breeder.all
  end

  # GET /breeders/1
  # GET /breeders/1.json
  def show
  end

  # GET /breeders/new
  def new
    @breeder = Breeder.new
  end

  # GET /breeders/1/edit
  def edit
  end

  # POST /breeders
  # POST /breeders.json
  def create
    @breeder = Breeder.new(breeder_params)

    respond_to do |format|
      if @breeder.save
        format.html { redirect_to @breeder, notice: 'Breeder was successfully created.' }
        format.json { render :show, status: :created, location: @breeder }
      else
        format.html { render :new }
        format.json { render json: @breeder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeders/1
  # PATCH/PUT /breeders/1.json
  def update
    respond_to do |format|
      if @breeder.update(breeder_params)
        format.html { redirect_to @breeder, notice: 'Breeder was successfully updated.' }
        format.json { render :show, status: :ok, location: @breeder }
      else
        format.html { render :edit }
        format.json { render json: @breeder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeders/1
  # DELETE /breeders/1.json
  def destroy
    @breeder.destroy
    respond_to do |format|
      format.html { redirect_to breeders_url, notice: 'Breeder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breeder
      @breeder = Breeder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breeder_params
      params.require(:breeder).permit(:name, :imageurl, :age, :breeds, :city, :father, :mother, :injectionurl, :health, :gender, :user_id, :user_email, :image)
    end
end

app/helpers/breeders_helper.rb
module BreedersHelper
end

app/views/breeders/_form.html.erb
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @breeder, html: { multipart: true } do |f| %>

      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :age %>
      <%= f.select(:age,@option = options_for_select([[''],['1 year - 2 years'],['2 years - 3 years'],['3 years - 4 years'],['4 years - 5 years'],['5 years - 6 years'],['over 6 years']],@breeder.age)) %>

      <%= f.label :gender %>
      <%= f.select(:gender,@option = options_for_select([['',''],['Male','0'],['Female','1']],@breeder.gender)) %>
     <br>
      <%= f.label :breeds %>
      <%= f.select(:breeds,@option = options_for_select([[''],['Labrador'],['German Shepherd'],['Beagle'],['Golden Retriever'],['Yorkshire Terrier'],['Bulldog'],['Box'],['Poodle'],['Others']],@breeder.breeds)) %>

      <%= f.label :city %>
      <%= f.select(:city,@option = options_for_select([[''],['Carlow'],['Cavan'],['Clare'],['Cork'],['Donegal'],['Dublin'],['Kerry'],['Kildare'],['Kilkenny'],['Laois'],['Leitrim'],['Limerick'],['Longford'],['Louth'],['Mayo'],['Meath'],['Monaghan'],['Offaly'],['Roscommon'],['Sligo'],['Tipperary'],['Waterford'],['Westmeath'],['Wexford'],['Wicklow']],@breeder.city)) %>
      <br>
      <%= f.label :father %>
      <%= f.text_field :father, class: 'form-control' %>

      <%= f.label :mother %>
      <%= f.text_field :mother, class: 'form-control' %>

      <%= f.label :imageurl %>
      <%= f.text_field :imageurl, class: 'form-control' %>

      <%= f.label :injectionurl %>
      <%= f.text_field :injectionurl, class: 'form-control' %>

      <%= f.label :health %>
      <%= f.number_field :health, class: 'form-control' %>

      
      <%= f.hidden_field(:user_id, :value=>current_user.id)  %>
      <%= f.hidden_field(:user_email, :value=>current_user.email)  %>


      <%= f.submit "Update breeder", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/breeders/edit.html.erb
<br>
<br>
<h1>Editing Breeder</h1>

<%= render 'form' %>

<%= link_to 'Show', @breeder %> |
<%= link_to 'Back', breeders_path %>

app/views/breeders/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>

<h1>Dogs for Breeding </h1>
<p>(1)You can add dogs for breeding. <a href="http://localhost:3000/breeders/new" class="btn btn-dark">
  Add Breeds  </a></p>
<p>(2)You can search a dog for breeding which matches your dog.</p>
<%= form_tag searched_path, method: :get do %>
    Search: <%= text_field_tag :search, params[:search], placeholder: "input breeds or city" %>&nbsp;&nbsp;&nbsp;&nbsp;<input class="btn btn-dark" name="commit" type="submit" value="Search">
<% end %>
  
    

<% @breeders.each_slice(3) do |breeders| %>
  <div class="row">
    <% breeders.each do |breeder| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to breeder do %>
              <%= image_tag breeder.image.url(:medium) %>
            <% end %>
          </div>
          <h2><%= link_to breeder.name, breeder %></h2>
          <h2>Owner: <%= link_to breeder.user_email, breeder.user %> </h2>

        </div>
      </div>
    <% end %>
  </div>
<% end %>


<%= link_to 'New Breeder', new_breeder_path %>

app/views/breeders/new.html.erb
<br>
<br>
<h1>New Breeder</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
 
    <%= form_for @breeder, html: { multipart: true } do |f| %>
    <form class="form-horizontal">
      <div class="form-group">
        <%= f.label :image,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.file_field :image, class: 'form-control' %>
        </div>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :name,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <br>
     
        &nbsp;&nbsp;&nbsp;<%= f.label :age, class: 'control-label' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= f.select(:age,@option = options_for_select([[''],['1 year - 2 years'],['2 years - 3 years'],['3 years - 4 years'],['4 years - 5 years'],['5 years - 6 years'],['over 6 years']],@breeder.age)) %>
        <br>
        &nbsp;&nbsp;&nbsp;<%= f.label :gender, class: 'control-label' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= f.select(:gender,@option = options_for_select([['',''],['Male','0'],['Female','1']],@breeder.gender)) %>
        <br>
        &nbsp;&nbsp;&nbsp;<%= f.label :breeds, class: 'control-label' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= f.select(:breeds,@option = options_for_select([[''],['Labrador'],['German Shepherd'],['Beagle'],['Golden Retriever'],['Yorkshire Terrier'],['Bulldog'],['Boxer'],['Poodle'],['Others']],@breeder.breeds)) %>
        <br>
        &nbsp;&nbsp;&nbsp;<%= f.label :city, class: 'control-label' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= f.select(:city,@option = options_for_select([[''],['Carlow'],['Cavan'],['Clare'],['Cork'],['Donegal'],['Dublin'],['Kerry'],['Kildare'],['Kilkenny'],['Laois'],['Leitrim'],['Limerick'],['Longford'],['Louth'],['Mayo'],['Meath'],['Monaghan'],['Offaly'],['Roscommon'],['Sligo'],['Tipperary'],['Waterford'],['Westmeath'],['Wexford'],['Wicklow']],@breeder.city)) %>
      <br>
      <div class="form-group">
        <%= f.label :father,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :father, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :mother,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :mother, class: 'form-control' %>
        </div>
      </div>
      
    
      <div class="field">
        &nbsp;&nbsp;&nbsp;<%= f.label :health %>
        <div id="star-rating">&nbsp;&nbsp;&nbsp;</div>
      </div>

      <div class="form-group">
        <%= f.label :imageurl,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :imageurl, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :injectionurl,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :injectionurl, class: 'form-control' %>
        </div>
      </div>
      
    
      
    
        
      <%= f.hidden_field(:user_id, :value=>current_user.id)  %>
      <%= f.hidden_field(:user_email, :value=>current_user.email)  %>

    
      <%= f.submit "Add breeds", class: "btn btn-primary" %>
  
    <% end %>
  </form>
</div>
</div>

<%= link_to 'Back', breeders_path %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'breeder[health]'
  });
</script>

app/views/breeders/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<div class="row">
  <aside class="col-md-7">
    <section >
    
      <%= image_tag @breeder.image.url(:medium) %>
    
    </section>
  </aside>
<div>
<h2>
  <strong>Name:</strong>
  <%= @breeder.name %>
</h2>

<p>
  <strong>Age:</strong>
  <%= @breeder.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @breeder.gender==0?"Male":"Female" %>
</p>

<p>
  <strong>Breeds:</strong>
  <%= @breeder.breeds %>
</p>

<p>
  <strong>City:</strong>
  <%= @breeder.city %>
</p>

<p>
  <strong>Father:</strong>
  <%= @breeder.father %>
</p>

<p>
  <strong>Mother:</strong>
  <%= @breeder.mother %>
</p>

<p>
  <strong>Health status:</strong>
  <div class="star-rating" data-score=<%= @breeder.health %> ></div>
  
</p>

<p>
  <strong>Injection certificate:</strong>
  <a href="http://cdn.lookanimals.com/pictures/dan.drydog.com/fanniemae/fannie-mae-vaccination-cert-2011.jpg">View</a>
</p>

<p>
  <strong>Owner email:</strong>
  <%= @breeder.user_email %>
</p>
</div>
</div>

<div class="row">
  <aside class="col-md-7">
    
    <h2><%= @breeder.comments.count %> Comments</h2>
    <%= render @breeder.comments %>

    <h3>Add a comment</h3>
    <%= form_for([@breeder, @breeder.comments.build]) do |f| %>
    <p>
      <%= f.label :body %></br>
      <%= f.text_area :body %>
    </p>
    </br>
    <%= f.submit "Create Comment", class: "btn btn-primary" %>
    <% end %>

    </aside>  
  </div>

<%= link_to 'Edit', edit_breeder_path(@breeder) %> |
<%= link_to 'Back', breeders_path %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>