config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :breeders do
    resources :comments
  end

  resources :products do
    resources :orders
  end

  
  
  resources :users
  root 'static_pages#home'
  
  get 'users'    => 'users#index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  match '/searched', to: 'search#search', via: 'get'
  match '/searchesed', to: 'searches#searches', via: 'get'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, styles: { large: "600x600>", medium: "400x400#", :thumb => "150x150#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    belongs_to :user
    has_many :orders
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:imageurl, :age, :breeds, :city, :father, :mother, :injectionurl, :health, :price, :gender, :user_id, :user_email, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @product, html: { multipart: true } do |f| %>
    
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>

      

      <%= f.label :age %>
      <%= f.select(:age,@option = options_for_select([[''],['1 month'],['2 months'],['3 months'],['4 months'],['5 months'],['6 months'],['6 months - 1 year']],@product.age)) %>

      <%= f.label :gender %>
      <%= f.select(:gender,@option = options_for_select([['',''],['Male','0'],['Female','1']],@product.gender)) %>

      <%= f.label :breeds %>
      <%= f.select(:breeds,@option = options_for_select([[''],['Labrador'],['German Shepherd'],['Beagle'],['Golden Retriever'],['Yorkshire Terrier'],['Bulldog'],['Box'],['Poodle'],['Others']],@product.breeds)) %>

      <%= f.label :city %>
      <%= f.select(:city,@option = options_for_select([[''],['Carlow'],['Cavan'],['Clare'],['Cork'],['Donegal'],['Dublin'],['Kerry'],['Kildare'],['Kilkenny'],['Laois'],['Leitrim'],['Limerick'],['Longford'],['Louth'],['Mayo'],['Meath'],['Monaghan'],['Offaly'],['Roscommon'],['Sligo'],['Tipperary'],['Waterford'],['Westmeath'],['Wexford'],['Wicklow']],@product.city)) %>

      <%= f.label :price %>
       <%= f.text_field :price, placeholder: "€", class: 'form-control' %>

  
    <%= f.label :father %>
    <%= f.text_field :father, class: 'form-control' %>

    <%= f.label :mother %>
    <%= f.text_field :mother, class: 'form-control' %>

    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl, class: 'form-control' %>
  
    <%= f.label :injectionurl %>
    <%= f.text_field :injectionurl, class: 'form-control' %>
 
    <%= f.label :health %>
    <%= f.number_field :health, class: 'form-control' %>

    <%= f.submit "Update product", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<br>
<br>
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>
<h1>Dogs for Sale</h1>
<p>(1)You can add dogs for sale.  <a href="http://localhost:3000/products/new" class="btn btn-dark btn-lg">
  Add Sale  </a></p>
<p>(2)You can buy a dog that you want.</p>

<%= form_tag searchesed_path, method: :get do %>
    Search: <%= text_field_tag :searches, params[:searches], placeholder: "input breeds or city" %>&nbsp;&nbsp;&nbsp;&nbsp;
      <input class="btn btn-dark" name="commit" type="submit" value="Search">

       <% end %>
    

<% @products.each_slice(3) do |products| %>
  <div class="row">
    <% products.each do |product| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to product do %>
              <%= image_tag product.image.url(:medium) %>
            <% end %>
          </div>
          <h2><%= link_to product.breeds, product %></h2>
          <h2>Seller: <%= link_to product.user_email, product.user %> </h2>

        </div>
      </div>
    <% end %>
  </div>
<% end %>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<br>
<br>
<h1>New Product</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @product, html: { multipart: true } do |f| %>
    
      <form class="form-horizontal">
      <div class="form-group">
        <%= f.label :image,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.file_field :image, class: 'form-control' %>
        </div>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :price,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :price, placeholder: "€", class: 'form-control' %>
        </div>
      </div>
      <br>
      
      &nbsp;&nbsp;&nbsp;<%= f.label :age, class: 'control-label' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= f.select(:age,@option = options_for_select([[''],['1 month'],['2 months'],['3 months'],['4 months'],['5 months'],['6 months'],['6 months - 1 year']],@product.age)) %>
        <br>
        &nbsp;&nbsp;&nbsp;<%= f.label :gender, class: 'control-label' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= f.select(:gender,@option = options_for_select([['',''],['Male','0'],['Female','1']],@product.gender)) %>
        <br>
        &nbsp;&nbsp;&nbsp;<%= f.label :breeds, class: 'control-label' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= f.select(:breeds,@option = options_for_select([[''],['Labrador'],['German Shepherd'],['Beagle'],['Golden Retriever'],['Yorkshire Terrier'],['Bulldog'],['Boxer'],['Poodle'],['Others']],@product.breeds)) %>
        <br>
        &nbsp;&nbsp;&nbsp;<%= f.label :city, class: 'control-label' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= f.select(:city,@option = options_for_select([[''],['Carlow'],['Cavan'],['Clare'],['Cork'],['Donegal'],['Dublin'],['Kerry'],['Kildare'],['Kilkenny'],['Laois'],['Leitrim'],['Limerick'],['Longford'],['Louth'],['Mayo'],['Meath'],['Monaghan'],['Offaly'],['Roscommon'],['Sligo'],['Tipperary'],['Waterford'],['Westmeath'],['Wexford'],['Wicklow']],@product.city)) %>
      <br>
      <div class="form-group">
        <%= f.label :father,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :father, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :mother,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :mother, class: 'form-control' %>
        </div>
      </div>
      
    
      <div class="field">
        &nbsp;&nbsp;&nbsp;<%= f.label :health %>
        <div id="star-rating">&nbsp;&nbsp;&nbsp;</div>
      </div>

      <div class="form-group">
        <%= f.label :imageurl,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :imageurl, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :injectionurl,class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :injectionurl, class: 'form-control' %>
        </div>
      </div>

      
      <%= f.hidden_field(:user_id, :value=>current_user.id)  %>
      <%= f.hidden_field(:user_email, :value=>current_user.email)  %>


      <%= f.submit "Add an product", class: "btn btn-primary" %>
    <% end %>
    </form>
  </div>
</div>
<%= link_to 'Back', products_path %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'product[health]'
  });
</script>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<div class="row">
  <aside class="col-md-6">
    <section >
    
      <%= image_tag @product.image.url(:medium) %>
    
    </section>
  </aside>

  <div>

<h2>
  <strong>Breeds:</strong>
  <%= @product.breeds %>
</h2>



<p>
  <strong>Age:</strong>
  <%= @product.age %>
</p>


<p>
  <strong>City:</strong>
  <%= @product.city %>
</p>

<p>
  <strong>Father:</strong>
  <%= @product.father %>
</p>

<p>
  <strong>Mother:</strong>
  <%= @product.mother %>
</p>



<p>
  <strong>Health status:</strong>
  <div class="star-rating" data-score=<%= @product.health %> ></div>
</p>

<p>
  <strong>Price: €</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @product.gender==0?"Male":"Female" %>
</p>

<p>
  <strong>Injection certificate:</strong>
  <a href="http://cdn.lookanimals.com/pictures/dan.drydog.com/fanniemae/fannie-mae-vaccination-cert-2011.jpg">View</a>
</p>

<p>
  <strong>Seller:</strong>
  <%= @product.user_email %>
</p>
<p>
  <%= link_to 'Buy now!', new_product_order_path(@product) %>
</p>
</div>
</div>

<div class="row">
  <aside class="col-md-7">
    
    <h3>Add a order</h3>
    <%= form_for([@product, @product.orders.build]) do |f| %>
    <p>
      <%= f.label :name %></br>
      <%= f.text_area :name %>
    </p>
    <p>
      <%= f.label :address %></br>
      <%= f.text_area :address %>
    </p>
    <p>
      <%= f.label :phone_number %></br>
      <%= f.text_area :phone_number %>
    </p>
    </br>
    <%= f.submit "Create Order", class: "btn btn-primary" %>
    <% end %>

    </aside>  
  </div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>