config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :breeders do
    resources :comments
  end

  resources :products do
    resources :orders
  end

  
  
  resources :users
  root 'static_pages#home'
  
  get 'users'    => 'users#index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  match '/searched', to: 'search#search', via: 'get'
  match '/searchesed', to: 'searches#searches', via: 'get'

end

app/views/layouts/_header.html.erb
<!--header-->
<div class="header">
  <div class="header-info">
    <div class="container">
    <div class="logo">
        <img src="assets/logo.png"  />
    </div>              
    </div>
  </div>
</div>
<div class="container">
         <div class="header-bottom">
              <div class="menu">
                <span class="menu-info"> </span>
                <ul class="cl-effect-21">
                  <li><%= link_to "HOME", root_path %></li>
                  <li><%= link_to "ABOUT", about_path %></li>                  
                  <li><%= link_to "CONTACT", contact_path %></li>
                  <% if logged_in? %>
                    <li><%= link_to "BREEDS", breeders_path %></li>
                    <li><%= link_to "SALES", products_path %></li>
                    <li><%= link_to "MY ACCOUNT", current_user %></li>
                    
                  <% else %>
                    <li><%= link_to "LOG IN", login_path %></li>
                  <% end %>
                </ul>
              </div>
          <!--script-nav -->  
              <script>
          $("span.menu-info").click(function(){
            $("ul.cl-effect-21").slideToggle("slow" , function(){
            });
          });
          </script>
          <!-- /script-nav -->
                    <div class="clearfix"> </div> 
       </div>
  </div>
<!--/header-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
      <head>
        <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
        <%= stylesheet_link_tag 'application', media: 'all',
                                               'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag "https://js.stripe.com/v2/" %>
        <%= csrf_meta_tags %>
        <%= tag :meta, :name => "stripe-key", :content => "pk_test_qK5YTtSXVzcRWTXMaVH7C2fk" %>
        <!--[if lt IE 9]>
          <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
          </script>
        <![endif]-->
      </head>
      <body>
        <%= render 'layouts/header' %>
        <div class="container">
                                               <!-- END NEW CODE  -->
          <%= yield %>
          
        </div>
      </body>
    </html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>